### ISSUE TITLE
Crash on non-Facebook-uploaded image

### ISSUE THREAD

**Issue by Eckankar** [DiSiqueira/TinderOnline#3]
The program crashes due to one of my profile images being uploaded through the app, rather than being pulled from Facebook.

```
panic: json: invalid use of ,string struct tag, trying to unmarshal "directupload" into int64

goroutine 1 [running]:
panic(0x62faa0, 0xc4203762c0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
main.checkError(0x7829a0, 0xc4203762c0)
        /home/sebbe/src/github.com/disiqueira/tinderonline/tinderonline.go:137 +0x5c
main.main()
        /home/sebbe/src/github.com/disiqueira/tinderonline/tinderonline.go:28 +0x175

```

In particular, one of my pictures has `"fbId":"directupload"`.

**Comment by d6o** [comment]
I removed fbid field until i can figure out how to handle this unstandardized field.

Updating the packages should fix the issue:

```
go get -u github.com/disiqueira/tindergo
go get -u github.com/disiqueira/tinderonline
```

**Comment by Eckankar** [comment]
That did indeed resolve the issue.

**Comment by d6o** [comment]
Thank you for the feedback!!
